BEGIN;
DROP TABLE IF EXISTS "role","lesson_thematic","user","thematic","sub_category","lesson","content";

CREATE TABLE "user" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "login" TEXT NOT NULL,    
    "email" TEXT NOT NULL UNIQUE,
    "password" TEXT NOT NULL UNIQUE,
    "role_id" INT NOT NULL DEFAULT '1',
    "created_at" timestamptz DEFAULT now(),
    "updated_at" timestamptz
);

CREATE TABLE "role"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "role" TEXT NOT NULL
);

CREATE TABLE "thematic"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "category" TEXT NOT NULL UNIQUE,    
    "created_at" timestamptz DEFAULT now(),
    "updated_at" timestamptz
);

CREATE TABLE "sub_category" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL UNIQUE,    
    "thematic_id" INT NOT NULL UNIQUE,
    "created_at" timestamptz DEFAULT now(),
    "updated_at" timestamptz   
);

CREATE TABLE "lesson"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" TEXT NOT NULL UNIQUE,    
    "sub_category_id" INT NULL,
    "user_id" INT NOT NULL,
    "content_id" INT NOT NULL,
    "created_at" timestamptz DEFAULT now(),
    "updated_at" timestamptz
);

CREATE TABLE "content" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "file_url" TEXT NOT NULL UNIQUE,
    "created_at" timestamptz DEFAULT now(),
    "updated_at" timestamptz
);

CREATE TABLE "lesson_thematic" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "lesson_id" INT NOT NULL REFERENCES "lesson" ("id"),
    "thematic_id" INT NOT NULL REFERENCES "thematic" ("id"),
    "created_at" timestamptz DEFAULT now(),
    "updated_at" timestamptz
);

ALTER TABLE "user"
    ADD FOREIGN KEY ("role_id") REFERENCES "role" ("id");

ALTER TABLE "sub_category"
    ADD FOREIGN KEY ("thematic_id") REFERENCES "thematic" ("id");

ALTER TABLE "lesson"
    ADD FOREIGN KEY("sub_category_id") REFERENCES "sub_category" ("id"),
    ADD FOREIGN KEY("user_id") REFERENCES "user" ("id"),
    ADD FOREIGN KEY("content_id") REFERENCES "content" ("id");

COMMIT;