BEGIN;
DROP TABLE IF EXISTS "user","thematic","sub_category","lesson","content";

CREATE TABLE "user" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "email" TEXT NOT NULL UNIQUE,
    "password" TEXT,
    "created_at" timestamptz DEFAULT now(),
    "updated_at" timestamptz
);

CREATE TABLE "thematic"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "category" TEXT NOT NULL UNIQUE,
    "lesson_id" INT,
    "created_at" timestamptz DEFAULT now(),
    "updated_at" timestamptz
);

CREATE TABLE "sub_category" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL UNIQUE,    
    "thematic_id" INT NOT NULL UNIQUE,
    "created_at" timestamptz DEFAULT now(),
    "updated_at" timestamptz   
);

CREATE TABLE "lesson"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" TEXT NOT NULL UNIQUE,
    "thematic_id" INT NOT NULL,
    "sub_category_id" INT NULL,
    "user_id" INT NOT NULL,
    "content_id" INT NOT NULL,
    "created_at" timestamptz DEFAULT now(),
    "updated_at" timestamptz
);

CREATE TABLE "content" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "file_url" TEXT NOT NULL UNIQUE,
    "created_at" timestamptz DEFAULT now(),
    "updated_at" timestamptz
);

ALTER TABLE "sub_category"
    ADD FOREIGN KEY ("thematic_id") REFERENCES "thematic" ("id");

ALTER TABLE "thematic"
    ADD FOREIGN KEY ("lesson_id") REFERENCES "lesson" ("id");


ALTER TABLE "lesson"
    ADD FOREIGN KEY("sub_category_id") REFERENCES "sub_category" ("id"),
    ADD FOREIGN KEY("user_id") REFERENCES "user" ("id"),
    ADD FOREIGN KEY("content_id") REFERENCES "content" ("id");

COMMIT;